"""empty message

Revision ID: 0472650ad039
Revises: 4fc25783a8d1
Create Date: 2026-05-07 19:57:05.457526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0472650ad039'
down_revision = '4fc25783a8d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('match_score', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_matches_status'))
        batch_op.create_index(batch_op.f('ix_matches_match_score'), ['match_score'], unique=False)
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_matches_match_score'))
        batch_op.create_index(batch_op.f('ix_matches_status'), ['status'], unique=False)
        batch_op.drop_column('match_score')

    # ### end Alembic commands ###
