"""Initial PostgreSQL schema

Revision ID: 40649d5e7441
Revises: 
Create Date: 2026-05-02 15:02:20.103090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40649d5e7441'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hobby',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hobby_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hobby', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hobby_hobby_name'), ['hobby_name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('visibility', sa.Boolean(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_joined_at'), ['joined_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_last_seen'), ['last_seen'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_visibility'), ['visibility'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user1_id', sa.Integer(), nullable=True),
    sa.Column('user2_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user2_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_user1_id'), ['user1_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_user2_id'), ['user2_id'], unique=False)

    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('favorite_user_id', sa.Integer(), nullable=True),
    sa.Column('favorited_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['favorite_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favorites_favorite_user_id'), ['favorite_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_favorites_favorited_at'), ['favorited_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_favorites_user_id'), ['user_id'], unique=False)

    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user1_id', sa.Integer(), nullable=True),
    sa.Column('user2_id', sa.Integer(), nullable=True),
    sa.Column('matched_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user2_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matches_matched_at'), ['matched_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_user1_id'), ['user1_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_user2_id'), ['user2_id'], unique=False)

    op.create_table('swipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('swiper_id', sa.Integer(), nullable=True),
    sa.Column('swipee_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=16), nullable=True),
    sa.Column('swiped_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['swipee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['swiper_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('swipe', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_swipe_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_swipe_swiped_at'), ['swiped_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_swipe_swipee_id'), ['swipee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_swipe_swiper_id'), ['swiper_id'], unique=False)

    op.create_table('user_hobbies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('hobby_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hobby_id'], ['hobby.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(length=64), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_location', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_location_latitude'), ['latitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_location_location_name'), ['location_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_location_longitude'), ['longitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_location_user_id'), ['user_id'], unique=True)

    op.create_table('user_looking_for',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('looking_for', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_looking_for', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_looking_for_looking_for'), ['looking_for'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_looking_for_user_id'), ['user_id'], unique=True)

    op.create_table('user_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('photo_url', sa.String(length=256), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_photo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_photo_photo_url'), ['photo_url'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_photo_uploaded_at'), ['uploaded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_photo_user_id'), ['user_id'], unique=False)

    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('min_age', sa.Integer(), nullable=True),
    sa.Column('max_age', sa.Integer(), nullable=True),
    sa.Column('gender_preference', sa.String(length=16), nullable=True),
    sa.Column('max_distance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_preferences_gender_preference'), ['gender_preference'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_preferences_max_age'), ['max_age'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_preferences_max_distance'), ['max_distance'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_preferences_min_age'), ['min_age'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_preferences_user_id'), ['user_id'], unique=True)

    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_profile_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_profile_dob'), ['dob'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_profile_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_profile_gender'), ['gender'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_profile_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_profile_user_id'), ['user_id'], unique=True)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_sent_at'), ['sent_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_sent_at'))
        batch_op.drop_index(batch_op.f('ix_messages_sender_id'))
        batch_op.drop_index(batch_op.f('ix_messages_is_read'))
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))

    op.drop_table('messages')
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_profile_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_profile_last_name'))
        batch_op.drop_index(batch_op.f('ix_user_profile_gender'))
        batch_op.drop_index(batch_op.f('ix_user_profile_first_name'))
        batch_op.drop_index(batch_op.f('ix_user_profile_dob'))
        batch_op.drop_index(batch_op.f('ix_user_profile_description'))

    op.drop_table('user_profile')
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_preferences_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_preferences_min_age'))
        batch_op.drop_index(batch_op.f('ix_user_preferences_max_distance'))
        batch_op.drop_index(batch_op.f('ix_user_preferences_max_age'))
        batch_op.drop_index(batch_op.f('ix_user_preferences_gender_preference'))

    op.drop_table('user_preferences')
    with op.batch_alter_table('user_photo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_photo_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_photo_uploaded_at'))
        batch_op.drop_index(batch_op.f('ix_user_photo_photo_url'))

    op.drop_table('user_photo')
    with op.batch_alter_table('user_looking_for', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_looking_for_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_looking_for_looking_for'))

    op.drop_table('user_looking_for')
    with op.batch_alter_table('user_location', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_location_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_location_longitude'))
        batch_op.drop_index(batch_op.f('ix_user_location_location_name'))
        batch_op.drop_index(batch_op.f('ix_user_location_latitude'))

    op.drop_table('user_location')
    op.drop_table('user_hobbies')
    with op.batch_alter_table('swipe', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_swipe_swiper_id'))
        batch_op.drop_index(batch_op.f('ix_swipe_swipee_id'))
        batch_op.drop_index(batch_op.f('ix_swipe_swiped_at'))
        batch_op.drop_index(batch_op.f('ix_swipe_action'))

    op.drop_table('swipe')
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matches_user2_id'))
        batch_op.drop_index(batch_op.f('ix_matches_user1_id'))
        batch_op.drop_index(batch_op.f('ix_matches_status'))
        batch_op.drop_index(batch_op.f('ix_matches_matched_at'))

    op.drop_table('matches')
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favorites_user_id'))
        batch_op.drop_index(batch_op.f('ix_favorites_favorited_at'))
        batch_op.drop_index(batch_op.f('ix_favorites_favorite_user_id'))

    op.drop_table('favorites')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_user2_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_user1_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_started_at'))

    op.drop_table('conversations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_visibility'))
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_updated_at'))
        batch_op.drop_index(batch_op.f('ix_users_last_seen'))
        batch_op.drop_index(batch_op.f('ix_users_joined_at'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('hobby', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hobby_hobby_name'))

    op.drop_table('hobby')
    # ### end Alembic commands ###
