"""empty message

Revision ID: 4fc25783a8d1
Revises: f083425d9cc6
Create Date: 2026-05-06 22:36:40.655111

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4fc25783a8d1'
down_revision = 'f083425d9cc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('swiper_id', sa.Integer(), nullable=True),
    sa.Column('swipee_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=16), nullable=True),
    sa.Column('action_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['swipee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['swiper_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('swiper_id', 'swipee_id', name='unique_like')
    )
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_likes_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_likes_action_at'), ['action_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_likes_swipee_id'), ['swipee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_likes_swiper_id'), ['swiper_id'], unique=False)

    with op.batch_alter_table('swipe', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_swipe_action'))
        batch_op.drop_index(batch_op.f('ix_swipe_swiped_at'))
        batch_op.drop_index(batch_op.f('ix_swipe_swipee_id'))
        batch_op.drop_index(batch_op.f('ix_swipe_swiper_id'))

    op.drop_table('swipe')
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_match', ['user1_id', 'user2_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_constraint('unique_match', type_='unique')

    op.create_table('swipe',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('swiper_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('swipee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('swiped_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['swipee_id'], ['users.id'], name=op.f('swipe_swipee_id_fkey')),
    sa.ForeignKeyConstraint(['swiper_id'], ['users.id'], name=op.f('swipe_swiper_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('swipe_pkey'))
    )
    with op.batch_alter_table('swipe', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_swipe_swiper_id'), ['swiper_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_swipe_swipee_id'), ['swipee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_swipe_swiped_at'), ['swiped_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_swipe_action'), ['action'], unique=False)

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_likes_swiper_id'))
        batch_op.drop_index(batch_op.f('ix_likes_swipee_id'))
        batch_op.drop_index(batch_op.f('ix_likes_action_at'))
        batch_op.drop_index(batch_op.f('ix_likes_action'))

    op.drop_table('likes')
    # ### end Alembic commands ###
