"""empty message

Revision ID: bae020a076b3
Revises: 0472650ad039
Create Date: 2026-05-07 21:11:26.750608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bae020a076b3'
down_revision = '0472650ad039'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=16), nullable=True))
        batch_op.create_index(batch_op.f('ix_matches_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matches_status'))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
