"""empty message

Revision ID: f083425d9cc6
Revises: 40649d5e7441
Create Date: 2026-05-06 22:03:49.763469

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f083425d9cc6'
down_revision = '40649d5e7441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_conversations_started_at'))
        batch_op.create_index(batch_op.f('ix_conversations_updated_at'), ['updated_at'], unique=False)
        batch_op.create_unique_constraint('unique_conversation', ['user1_id', 'user2_id'])
        batch_op.drop_column('started_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint('unique_conversation', type_='unique')
        batch_op.drop_index(batch_op.f('ix_conversations_updated_at'))
        batch_op.create_index(batch_op.f('ix_conversations_started_at'), ['started_at'], unique=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('last_message')

    # ### end Alembic commands ###
